export const getGameExample = [
  {
    id: 213,
    subcategory: '반장전',
    category: '4마',
    players: [
      {
        playerName: '김철수A',
        nickname: '김철수',
        seat: 0,
        rank: 3,
        score: 25000,
      },
      {
        playerName: '김영희A',
        nickname: '김영희',
        seat: 1,
        rank: 1,
        score: 37200,
      },
      {
        playerName: '홍길동A',
        nickname: '홍길동',
        seat: 2,
        rank: 4,
        score: 11000,
      },
      {
        playerName: '홍길순A',
        nickname: '홍길순',
        seat: 3,
        rank: 2,
        score: 26800,
      },
    ],
    note: null,
  },
];

export const getDetailedGameExample = {
  id: 133,
  category: '4마',
  subcategory: '반장전',
  players: [
    {
      playerName: '홍길동A',
      nickname: '홍길동',
      seat: 0,
      rank: 1,
      score: 73000,
      ratingDiff: null,
    },
    {
      playerName: '홍길순A',
      nickname: '홍길순',
      seat: 1,
      rank: 2,
      score: 25000,
      ratingDiff: null,
    },
    {
      playerName: '김철수A',
      nickname: '김철수',
      seat: 2,
      rank: 3,
      score: 25000,
      ratingDiff: null,
    },
    {
      playerName: '김영희A',
      nickname: '김영희',
      seat: 3,
      rank: 4,
      score: -23000,
      ratingDiff: null,
    },
  ],
  note: null,
  createdAt: '2024-11-02T09:02:45.324Z',
  yakuman: [
    {
      id: 6,
      yakuman: ['스안커 단기'],
      round: '동 1국 0본장',
    },
    {
      id: 7,
      yakuman: ['녹일색'],
      round: null,
    },
  ],
};

export const playerStatisticsExample = [
  {
    id: 22350,
    playerName: '홍길동A',
    nickname: '홍길동',
    category: '4마',
    rating: '-59.75',
    averageRating: '-9.958',
    averageScore: '18800.00',
    maxScore: 38400,
    minScore: -6000,
    count: '6',
    first: '1',
    second: '1',
    third: '2',
    fourth: '2',
    tobi: '1',
  },
  {
    id: 26354,
    playerName: '김철수A',
    nickname: '김철수',
    category: '3마',
    rating: '20.60',
    averageRating: '3.433',
    averageScore: '38433.33',
    maxScore: 76700,
    minScore: -1100,
    count: '6',
    first: '2',
    second: '2',
    third: '2',
    fourth: '0',
    tobi: '1',
  },
];
