import type { Metadata } from "next";
import AppBar from "./appbar";
import { Box } from "@mui/material";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <AppBar />
          <Box
            component="main"
            sx={{ flexGrow: 1, padding: { xs: "4.5rem", sm: "6rem" } }}
          >
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  );
}
