import type { Metadata } from "next";
import "./globals.css";
import AppBar from "./appbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import RootThemeProvider from "./theme";
import { Box } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <AppRouterCacheProvider>
          <RootThemeProvider>
            <AppBar />
            <Box component="main" sx={{ flexGrow: 1, padding: "6rem" }}>
              {children}
            </Box>
          </RootThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
